title: My page of github
author: Heber Luna
email: heber.luna.t@gmail.com
description: > this is my new page of github

# social links
twitter_username: your-twitter-handle
github_username:  Heber Luna

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
